// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwsysveeoldxaafooavv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3c3lzdmVlb2xkeGFhZm9vYXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjM2MzAsImV4cCI6MjA1OTQ5OTYzMH0.79muaKISjTRIUIIY5W2qVdWcb_VcXim-On_0CHEnNNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);